
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/focal64"
  
   config.vm.provider "virtualbox" do |vb|
     
	 vb.name = "javacd-lab"
	 
	 # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  
     # Customize the amount of memory on the VM:
     vb.memory = "16000"
	 
     # Customize the number of CPU
     vb.cpus = 6
	 
     # Video Memory (Important)
     vb.customize ["modifyvm", :id, "--vram", "90"]
	 
     # Clipboard
     vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
	 
  end
  
  # Install the GUI, VirtualBox Tools
  config.vm.provision "shell", path: "provisioners/setup.sh"
  
  # Position Configuration Files
  config.vm.provision "file", source: "jenkins/admin.groovy", destination: "/home/vagrant/"
  config.vm.provision "file", source: "jenkins/plugins.txt", destination: "/home/vagrant/"
  config.vm.provision "file", source: "manifests/argocd.yaml", destination: "/home/vagrant/"
  config.vm.provision "file", source: "manifests/ingress.yaml", destination: "/home/vagrant/"
  config.vm.provision "file", source: "manifests/flagsmith-ingress.yaml", destination: "/home/vagrant/"
  
  # Install Groovy
  #config.vm.provision "shell", path: "setup_groovy.sh"
  
  # Install Docker
  config.vm.provision "shell", path: "provisioners/setup_docker.sh"

  # Install Java + Jenkins
  config.vm.provision "shell", path: "provisioners/setup_java.sh"

  # Install k3d
  config.vm.provision "shell", path: "provisioners/setup_k3d.sh"
      
  # Install ArgoCd
  config.vm.provision "shell", path: "provisioners/setup_argo.sh"
  
  # Install ArgoCd in Staging
  config.vm.provision "shell", path: "provisioners/setup_argo_staging.sh"

  # Install Flagsmith
  config.vm.provision "shell", path: "provisioners/setup_flagsmith.sh"
  
  # Install Flagsmith Staging
  config.vm.provision "shell", path: "provisioners/setup_flagsmith_staging.sh"
  
  # Create Keys for GitHub
  config.vm.provision "shell", path: "provisioners/setup_ssh.sh"
  
  # Add Course Materials and HUB
  config.vm.provision "shell", path: "provisioners/setup_lab_materials.sh"
  
  # Restart
  config.vm.provision "shell", inline: "sudo shutdown -r now"
  
end
